### ISSUE TITLE
Current Project is not working. Having error..!!

### ISSUE THREAD

**Issue by irushabh** [gismofx/toast_ui.blazor_calendar#1]
Hello,

I am trying to run your pull project and I am having an error regarding .NET SDK . I have also tried by using nuget package download. Same error I am getting. 

Can you please help me out of this issue.

![image](https://user-images.githubusercontent.com/4029082/116583322-392a1080-a8e4-11eb-9f56-3cdc09ce33d6.png)

**Comment by gismofx** [comment]
I'll try to help :) 
Did you download the whole repo and run the sample project? 

Otherwise, try to make a new Blazor server project from template and pull in the nuget and setup per the readme.

**Comment by irushabh** [comment]
Hello,

Yes, I have did exactly like you mentioned above comment. But no luck..!!

**Comment by gismofx** [comment]
I will try on my end later today and let you know, but the included test project should run. 

Please stand by.

**Comment by irushabh** [comment]
Hello,

No Worries. I will wait for your response. 

Please find my sample project on below URL: 
https://github.com/irushabh/Test_CalendarProj

Thanks Again.. Really great work by You..!!!

Rush

**Comment by gismofx** [comment]
Hi @irushabh I just created tested on my end and created a new Blazor Server project and pulled in the latest nuget via `Install-Package toast_ui.blazor_calendar -Version 1.0.0-beta1.1`. 

Just drop in `<TUICalendar/>` in index with no parameters and it should load.

Also, make sure you have the latest package installed.

Also, I tried to open that rar file, but I got some file corruption error from winrar.

**Comment by irushabh** [comment]
Hello,

Thank for your help. it's working now 
But still I cannot set appointment just like your screen shot. I can drag and select time slot but I don't see popup to setup event name and dates and time.

Can you please help me out on this.?

Thanks,
Rush

**Comment by gismofx** [comment]
Great!

You have to enable the pop-ups via the calendar options class. 

Check out the test project viewmodel class around line 90.

https://github.com/gismofx/toast_ui.blazor_calendar/blob/main/toast_ui.blazor_calendar.TestProject/toast_ui.blazor_calendar.TestProject/ViewModels/CalendarViewModel.cs

**Comment by irushabh** [comment]
Thanks Man..!! 
Really appreciated.!!
