### ISSUE TITLE
Define a month in calendaroptions generate a error

### ISSUE THREAD

**Issue by ezequielmerecias** [gismofx/toast_ui.blazor_calendar#13]
//Set the Calendar Options
            CalendarOptions = new TUICalendarOptions()
            {
                useCreationPopup = true,
                useDetailPopup = true,
                week = new TUIWeekOptions()
                {
                    hourEnd = 24,
                    hourStart = 0,
                    daynames = new string[] { "Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" },
                    startDayOfWeek = 1
                },
                month = new TUIMonthOptions()
                {
                    daynames = new string[] { "Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" },
                    startDayOfWeek = 1,
                    narrowWeekend = true
                },
                ...
                
When you want to initialize a Month, when you change ViewModel.CalendarViewName generate a error.

**Comment by gismofx** [comment]
Thanks! Error in c# or in JS? Can you please share exact steps to reproduce error?

I'll take a look at this tomorrow and try to fix.

**Comment by ezequielmerecias** [comment]
In c#
when you define the props in Month when calendar loaded crashed.
If you don't define a Month the calendar works fine.

**Comment by ezequielmerecias** [comment]
I worked with Calendar in Js and works without any problem .

**Comment by gismofx** [comment]
@ezequielmerecias I found the issue. Some properties in  `TUIMonthOptions`, if they are not defined(i.e. null), cannot explicitly be null in the TUI JS side, they must be `undefined`. I am working on a custom JsonConverter for these properties so they are not sent to JS side via the interop. Stay tuned..

**Comment by gismofx** [comment]
@ezequielmerecias Problem resolved! I'll push and update and NuGet soon and tag you.
![image](https://user-images.githubusercontent.com/6783791/155899477-66623fa5-2d9e-4314-be56-ddb602bbe3db.png)

**Comment by sanongpost** [comment]
@gismofx  I am using your calendar in Blazor, Beta version 
Install-Package toast_ui.blazor_calendar -Version 1.0.0-beta1.4

I am facing
-When click to add schedule. the dialog layout is not inline, with picture of locker appear. I cannot get rid of it.
-How can I intercept click-event/ save event in order to save calendar schedule

Pls advise / sanongpost@hotmail.com

![UI_Calendar](https://user-images.githubusercontent.com/48399638/156915431-a6e4cdd4-05f7-4b26-bfe8-548b47a197cc.png)

**Comment by gismofx** [comment]
@sanongpost Please create new issue(s) for your two questions. Your second question is solved by using the EventCallbacks in the TUICalendar Component. Have a look here: https://github.com/gismofx/toast_ui.blazor_calendar/blob/acd6dcc45b23481fb41d008bbd8fedb198db8eca/toast_ui.blazor_calendar/TUICalendar.razor.cs#L78
