### ISSUE TITLE
Layout of schedule Dialog not adjusted - see attached image

### ISSUE THREAD

**Issue by sanongpost** [gismofx/toast_ui.blazor_calendar#15]
@gismofx  i created a new issue which may not an issue to you i think.

When you click to add/edit schedule, the dialog shown dont line up properly this may due to css not loaded. I have follow instruction from Nuget.

in _host.cshtml

   <link href="_content/toast_ui.blazor_Calendar/TUI.blazorCalendar.css" rel="stylesheet">
  <script src="_content/toast_ui.blazor_calendar/TUI.blazor_calendar.min.js"></script>

Pls advise.
thank you.

![UI_Calendar](https://user-images.githubusercontent.com/48399638/156931243-2c05a1d4-61c3-4162-ad42-d316890bb343.png)

**Comment by sanongpost** [comment]
i forget, css is also in same file.

  < link href="_content/toast_ui.blazor_Calendar/TUI.blazorCalendar.css" rel="stylesheet">

**Comment by gismofx** [comment]
@sanongpost definitely and CSS issue. Can you make a sample project and share that I can work on? I need to work on the CSS and JS building process in NPM to isolate the CSS.

**Comment by vgck** [comment]
I just came across this issue myself. If he is using MudBlazor, it is due to conflicting stylesheets. I was able to resolve it by resetting the letter-spacing:

div {
    letter-spacing: initial;
}

**Comment by gismofx** [comment]
@vgck Thanks! 

There's something I can tweak in NPM build steps to better isolate the CSS. 

Looks like someone may have solved it and I asked for a PR, but I will look into it myself too. https://stackoverflow.com/a/71166698/997088

**Comment by sanongpost** [comment]
Hi.

 

Yes the project is built using Mudblazor. 

I have added  as suggest and it is reset as designed.

 

Thank you

 

Regards

 

Sanong

**Comment by gismofx** [comment]
@vgck  @sanongpost I also use MudBlazor. I looked through the CSS in TUI and it all seems to be unique. Can you make a sample project which has this issue and also comment how you fixed it? I'd like to see where this issue is coming from. 

Also, the latest Nuget Package is now Net6.

**Comment by sanongpost** [comment]
Hi,

I try same but no point look thru it.

You can just add on the calendar razor page.

 

<style>

div { letter-spacing: initial; }

</style>

 

That resolve issue to me.

**Comment by vgck** [comment]
@gismofx Attached is a new project with latest version of toast_ui.blazor_calendar and MudBlazor reproducing this issue. MudBlazor applies a letter-spacing style to the body tag which gets inherited by the tui div tags.

[Test.zip](https://github.com/gismofx/toast_ui.blazor_calendar/files/8208691/Test.zip)

**Comment by gismofx** [comment]
@vgck Thanks! I will take a look. I wonder if there is some harmless adjustment in MB we could make..or if I can somehow insert  that css style to the css file when I compile this component.

**Comment by sanongpost** [comment]
Thank  ***@***.***> @gismofx/toast_ui.blazor_calendar

 

Could be please advise usage on some of  callback like below, I could not find any reference:

*	OnClickCalendarEventOrTask
*	OnChangeCalendarEventOrTask
*	OnCreateCalendarEventOrTask
*	OnDeleteCalendarEventOrTask

 

Intention of the app is to load from SQL/ update / delete event and save to SQL server

 

Thank you,

**Comment by sanongpost** [comment]
Yes, I just have created.

 

Suggestion/Advise on Component customization #17

**Comment by gismofx** [comment]
@vgck @sanongpost I've updated the nuget package to add isolated css to the component and I tested with your test project. Issue went away. Please try the latest nuget without the added style and let me know.

Thanks!

**Comment by sanongpost** [comment]
What is latest version  ? I cannot find it from the console.

**Comment by gismofx** [comment]
Install-Package toast_ui.blazor_calendar -Version 1.0.0-beta2.1
