### ISSUE TITLE
maybe issue on linux?

### ISSUE THREAD

**Issue by nebula2** [gismofx/toast_ui.blazor_calendar#19]
Hey,
I am trying to publish a webapp which uses this. webapp is hosted on a linux machine.
And it looks kind of weird :-|
![image](https://user-images.githubusercontent.com/5841525/160290627-9472ee5d-bd0a-4d29-ac5b-1c5be944a83f.png)

May it be that this has something to do with this here?
![image](https://user-images.githubusercontent.com/5841525/160290661-65abf95d-4d65-4021-934d-fd7b6b411b5d.png)

.."_Calendar" and "_calendar"

**Comment by gismofx** [comment]
@nebula2 Thanks! Are you using Nuget package or from source? 

Anyway, you're probably right because Linux is case-sensitive. I'll be able to take a look this evening and see what I need to tweak. If you happen to figure it out what needs to change, please let me know.

**Comment by nebula2** [comment]
hey, using it from nuget. normally i would add more details but time is not on my side today :/

**Comment by gismofx** [comment]
@nebula2 change your reference in the head to `<link href="_content/toast_ui.blazor_calendar/TUI.blazorCalendar.css" rel="stylesheet">`  There was a typo in the readme having an uppercase C.

**Comment by nebula2** [comment]
Perfect! That fixed it :)
![image](https://user-images.githubusercontent.com/5841525/160324044-5e0425f8-813a-471e-8e58-b1cedcb57dfa.png)

Thank you very much 😊
