### ISSUE TITLE
Consider updating README.md TuiCalendar.css tag

### ISSUE THREAD

**Issue by Ghevi** [gismofx/toast_ui.blazor_calendar#2]
Unless I'm missing something, it should be:
`    <link href="_content/toast_ui.blazor_calendar/TUI.blazorCalendar.css" rel="stylesheet">
`

**Comment by gismofx** [comment]
Nice find! You're correct! Thank you @Ghevi!

I updated the readme.

**Comment by Ghevi** [comment]
You're welcome. May I ask you if it is possible to customize the calendar theme? I see that the Class TUIThemeConfig is empty.
Is there any way to get the calendar object with javascript and call their Api?

**Comment by gismofx** [comment]
Can you open up a new issue/Feature Request(s) and we can discuss there? 

I haven't messed with the theme too much. I think I just need to wrap that class and add it to the constructor. 

Yes, you can call the Tui Api. @ref is a reference to the calendar DOM element, but we need to add the calls to the Calendar Interop Service for the functions you want to access.
