### ISSUE TITLE
Can't run test project 

### ISSUE THREAD

**Issue by Kistelekig98** [gismofx/toast_ui.blazor_calendar#22]
When I try to run the test project, the following line throws an exception: TUICalendar.razor.cs:317

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
System.Collections.Generic.Queue<T>.Dequeue(...) returned null.
```

If I comment the whole OnParametersSetAsync() method, the program seems to run correctly.

**Comment by gismofx** [comment]
@Kistelekig98 Is this in debug or release mode?

If you try in release mode does it work?

I do see an issue in that method and need to move the `while(...` inside the try/catch. I'll fix this evening.

**Comment by Kistelekig98** [comment]
@gismofx Yes, thanks.
