### ISSUE TITLE
No such property {currentSchedule.Id} in TUICalendar.razor.cs

### ISSUE THREAD

**Issue by paulsterling** [gismofx/toast_ui.blazor_calendar#3]
Minor issue where the property `Id` is referenced for the `TUISchedule` model which throws an exception and causes any custom code attached to the `UpdateSchedule` event to be skipped.

https://github.com/gismofx/toast_ui.blazor_calendar/blob/main/toast_ui.blazor_calendar/TUICalendar.razor.cs#L268

Will fix and add a PR shortly.

**Comment by gismofx** [comment]
@paulsterling nuget package updated
