### ISSUE TITLE
NpmJS get published with unnecessary files

### ISSUE THREAD

**Issue by SeanFeldman** [gismofx/toast_ui.blazor_calendar#37]
![image](https://user-images.githubusercontent.com/1309622/172983468-00c07d93-4740-48a8-b893-28bad5d3e4ad.png)
![image](https://user-images.githubusercontent.com/1309622/172983498-2329acbe-0c00-4564-8b95-83bb7794fb9a.png)

**Comment by gismofx** [comment]
Thanks! I'll take a look in the Project file(s) to make sure it's not copied to over during build.
